name: Build and publish docker images
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: lab-4.5.4
  NORTH_TOOL_DIR: src/nomad_north_voila/north_tools/voila_north_tool

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write

jobs:
  build:
    name: voila_north_tool image
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }} # list
      labels: ${{ steps.meta.outputs.labels }} # list
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
          show-progress: true
          submodules: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          # set latest tag for main branch and tags
          # https://github.com/docker/metadata-action?tab=readme-ov-file#image-name-and-tag-sanitization
          tags: |
            type=ref,event=tag
            type=raw,value=main,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          flavor: |
            latest=auto

      # https://docs.docker.com/build/ci/github-actions/share-image-jobs/
      # https://github.com/docker/build-push-action
      - name: Build and publish voila_north_tool image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.NORTH_TOOL_DIR }}/Dockerfile
          build-args: |
            IMAGE_TAG=${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
